# Generated by Django 4.1.13 on 2024-03-11 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('csv_file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(default='In Progress', max_length=100)),
                ('can_download', models.BooleanField(default=False)),
                ('file_location_old', models.CharField(blank=True, max_length=255)),
                ('file_location_with_status', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
