# Generated by Django 4.1.13 on 2024-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_file_location_with_status_csvfile_new_file_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
