# Generated by Django 4.1.13 on 2024-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_csvfile__id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=3)),
                ('college', models.CharField(max_length=128)),
                ('licenseNum', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('provDocID', models.CharField(max_length=150, unique=True)),
                ('prescriptions', models.JSONField(default=list)),
                ('language', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedPrescriberID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provDocID', models.CharField(max_length=150, unique=True)),
                ('province', models.CharField(max_length=3)),
                ('initials', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
