# Generated by Django 4.1.13 on 2024-03-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_csvfile__id_remove_csvfile_csv_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
