# Generated by Django 4.1.13 on 2024-03-10 18:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="actionRequired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="dpass",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="prescribersID",
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
