# Generated by Django 4.1.13 on 2024-03-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_user_perscribersid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name="Practitioner",
        ),
    ]
