# Generated by Django 4.1.13 on 2024-03-10 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_perscriber_delete_practitioner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perscriber",
            old_name="email",
            new_name="provDocID",
        ),
    ]
