# Generated by Django 4.1.13 on 2024-03-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_email_perscriber_provdocid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Perscriber",
            new_name="Prescriber",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
