# Generated by Django 4.1.13 on 2024-03-12 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_rename_perscriber_prescriber_user_city_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="perscribersID",
        ),
    ]
