# Generated by Django 4.1.13 on 2024-03-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_user_prescribersid"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriber",
            name="email",
            field=models.CharField(default="", max_length=128),
        ),
    ]
