# Generated by Django 4.1.13 on 2024-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_prescriber_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriber",
            name="firstName",
            field=models.CharField(default="", max_length=128),
        ),
    ]
