# Generated by Django 4.1.13 on 2024-03-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_prescriber_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prescribersID',
        ),
    ]
