# Generated by Django 4.1.13 on 2024-03-24 19:46

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_user_prescribersid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prescriptionIDs',
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
